// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1yOc6nJ_trmv_S9vgwY6oOPYCjk-ikrg',
    appId: '1:1055868701225:web:fe4ebf3cdda59e59146a38',
    messagingSenderId: '1055868701225',
    projectId: 'generic--bharat',
    authDomain: 'generic--bharat.firebaseapp.com',
    storageBucket: 'generic--bharat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgApAjvNFakkdJ8rTjAw7irvlmVA8tOOU',
    appId: '1:1055868701225:android:1d8cb38386208553146a38',
    messagingSenderId: '1055868701225',
    projectId: 'generic--bharat',
    storageBucket: 'generic--bharat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1fZ0qYGbeeGeB81V_8qHwM1hN5nwu7cg',
    appId: '1:1055868701225:ios:8c1916c270a62cfc146a38',
    messagingSenderId: '1055868701225',
    projectId: 'generic--bharat',
    storageBucket: 'generic--bharat.firebasestorage.app',
    iosBundleId: 'com.BdsInfotech.GenricBharat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1fZ0qYGbeeGeB81V_8qHwM1hN5nwu7cg',
    appId: '1:1055868701225:ios:8c1916c270a62cfc146a38',
    messagingSenderId: '1055868701225',
    projectId: 'generic--bharat',
    storageBucket: 'generic--bharat.firebasestorage.app',
    iosBundleId: 'com.BdsInfotech.GenricBharat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1yOc6nJ_trmv_S9vgwY6oOPYCjk-ikrg',
    appId: '1:1055868701225:web:ea290485d3154bcc146a38',
    messagingSenderId: '1055868701225',
    projectId: 'generic--bharat',
    authDomain: 'generic--bharat.firebaseapp.com',
    storageBucket: 'generic--bharat.firebasestorage.app',
  );
}
